# Generated by Django 5.0.7 on 2026-09-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True, verbose_name='clave')),
                ('file_name', models.CharField(max_length=255, verbose_name='archivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='tipo MIME')),
                ('data', models.BinaryField(verbose_name='contenido')),
                ('size', models.PositiveBigIntegerField(verbose_name='tamaño (bytes)')),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='categoría')),
                ('is_public', models.BooleanField(default=True, verbose_name='público')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'activo visual',
                'verbose_name_plural': 'activos visuales',
                'db_table': 'activos_visuales',
                'ordering': ['key'],
            },
        ),
    ]
