# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Compra"),
                            ("sale", "Venta"),
                            ("adjustment", "Ajuste"),
                            ("return", "Devolucion"),
                            ("waste", "Merma"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="cantidad")),
                ("previous_stock", models.PositiveIntegerField(verbose_name="stock anterior")),
                ("new_stock", models.PositiveIntegerField(verbose_name="stock nuevo")),
                ("reason", models.CharField(max_length=255, verbose_name="motivo")),
                (
                    "reference",
                    models.CharField(blank=True, max_length=100, verbose_name="referencia"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"], name="stock_move_product_created_idx"
                    ),
                    models.Index(
                        fields=["movement_type", "-created_at"], name="stock_move_type_created_idx"
                    ),
                    models.Index(fields=["reference"], name="stock_move_reference_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="stock_move_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("previous_stock__gte", 0)), name="stock_move_previous_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("new_stock__gte", 0)), name="stock_move_new_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("movement_type__in", ["purchase", "return"]),
                        (
                            "new_stock",
                            django.db.models.expressions.CombinedExpression(
                                models.F("previous_stock"), "+", models.F("quantity")
                            ),
                        ),
                    ),
                    models.Q(
                        ("movement_type__in", ["sale", "waste"]),
                        (
                            "previous_stock",
                            django.db.models.expressions.CombinedExpression(
                                models.F("new_stock"), "+", models.F("quantity")
                            ),
                        ),
                    ),
                    models.Q(
                        ("movement_type", "adjustment"),
                        (
                            "new_stock",
                            django.db.models.expressions.CombinedExpression(
                                models.F("previous_stock"), "+", models.F("quantity")
                            ),
                        ),
                    ),
                    models.Q(
                        ("movement_type", "adjustment"),
                        (
                            "previous_stock",
                            django.db.models.expressions.CombinedExpression(
                                models.F("new_stock"), "+", models.F("quantity")
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="stock_move_balances_match",
            ),
        ),
    ]
