# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False, max_length=20, unique=True, verbose_name="numero de pedido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queue", "En cola"),
                            ("confirmed", "Confirmado"),
                            ("prep", "En preparacion"),
                            ("ready", "Listo"),
                            ("delivered", "Entregado"),
                            ("cancelled", "Cancelado"),
                            ("nopickup", "No retirado"),
                        ],
                        default="queue",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("priority", "Prioridad"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="prioridad",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Retiro en cafeteria"),
                            ("delivery", "Delivery interno"),
                        ],
                        default="pickup",
                        max_length=20,
                        verbose_name="metodo de entrega",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="total",
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(default=5, verbose_name="tiempo estimado (min)"),
                ),
                ("note", models.TextField(blank=True, verbose_name="nota")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="nombre del producto"),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="cantidad")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio unitario",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="nota")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                        verbose_name="pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de pedido",
                "verbose_name_plural": "items de pedido",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.OrderItem",
                to="products.product",
                verbose_name="productos",
            ),
        ),
        migrations.CreateModel(
            name="OrderItemAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "addon_name",
                    models.CharField(max_length=100, verbose_name="nombre del adicional"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio unitario",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="cantidad")),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_snapshots",
                        to="products.addon",
                        verbose_name="adicional",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_addons",
                        to="orders.orderitem",
                        verbose_name="item de pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "adicional de item",
                "verbose_name_plural": "adicionales de items",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queue", "En cola"),
                            ("confirmed", "Confirmado"),
                            ("prep", "En preparacion"),
                            ("ready", "Listo"),
                            ("delivered", "Entregado"),
                            ("cancelled", "Cancelado"),
                            ("nopickup", "No retirado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, verbose_name="fecha")),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="nota")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cambiado por",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de estado",
                "verbose_name_plural": "historial de estados",
                "ordering": ["changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order", "product"], name="order_item_order_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="order_item_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)), name="order_item_unit_price_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "-created_at"], name="order_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "-created_at"], name="order_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_method", "status"], name="order_delivery_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("total__gte", 0)), name="order_total_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("estimated_time__gte", 0)), name="order_estimated_time_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitemaddon",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="order_item_addon_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitemaddon",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)), name="order_item_addon_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitemaddon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("addon__isnull", False)),
                fields=("order_item", "addon"),
                name="order_item_addon_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(fields=["order", "changed_at"], name="order_history_order_time_idx"),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["status", "-changed_at"], name="order_history_status_time_idx"
            ),
        ),
    ]
