# Generated by Django 5.0.7 on 2026-09-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='detalle_pedidos',
        ),
        migrations.AlterModelTable(
            name='orderitemaddon',
            table='detalle_pedido_adicionales',
        ),
        migrations.AlterModelTable(
            name='orderstatushistory',
            table='historial_estado_pedidos',
        ),
    ]
