# Generated by Django 5.0.7 on 2026-09-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_alter_orderitem_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('queue', 'En cola'), ('confirmed', 'Confirmado'), ('prep', 'En preparacion'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('nopickup', 'No retirado')], default='confirmed', max_length=20, verbose_name='estado'),
        ),
    ]
