# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(blank=True, max_length=200, verbose_name="nombre del usuario"),
                ),
                ("action", models.CharField(max_length=200, verbose_name="acción")),
                ("target", models.CharField(blank=True, max_length=200, verbose_name="objetivo")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="detalles")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dirección IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="fecha")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogProxy",
            fields=[],
            options={
                "verbose_name": "auditoría",
                "verbose_name_plural": "auditoría",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("audit.auditlog",),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created_at"], name="audit_created_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "-created_at"], name="audit_user_created_idx"),
        ),
    ]
