# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="codigo del proveedor"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio de costo",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="principal")),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor de producto",
                "verbose_name_plural": "proveedores de productos",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="persona de contacto"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ingrese un numero telefonico valido.",
                                regex="^\\+?[0-9()\\-\\s]{7,25}$",
                            )
                        ],
                        verbose_name="telefono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electronico"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="direccion")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="identificacion fiscal"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["active", "name"], name="supplier_active_name_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("tax_id__isnull", False), models.Q(("tax_id", ""), _negated=True)
                ),
                fields=("tax_id",),
                name="supplier_tax_id_unique",
            ),
        ),
        migrations.AddField(
            model_name="productsupplier",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_links",
                to="suppliers.supplier",
                verbose_name="proveedor",
            ),
        ),
        migrations.AddIndex(
            model_name="productsupplier",
            index=models.Index(fields=["product", "active"], name="ps_product_active_idx"),
        ),
        migrations.AddIndex(
            model_name="productsupplier",
            index=models.Index(fields=["supplier", "active"], name="ps_supplier_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(
                fields=("product", "supplier"), name="product_supplier_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_price__gte", 0)), name="product_supplier_cost_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("is_primary", True)),
                fields=("product",),
                name="one_primary_supplier_product",
            ),
        ),
    ]
