# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="habilitado")),
                ("start_time", models.TimeField(default="09:00", verbose_name="hora de inicio")),
                ("end_time", models.TimeField(default="09:45", verbose_name="hora de fin")),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacidad maxima",
                    ),
                ),
                (
                    "current_capacity",
                    models.PositiveIntegerField(default=0, verbose_name="capacidad actual"),
                ),
                (
                    "delivery_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de dias de la semana habilitados para delivery.",
                        verbose_name="dias de entrega",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
            ],
            options={
                "verbose_name": "configuracion de delivery",
                "verbose_name_plural": "configuraciones de delivery",
            },
        ),
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("piso", models.PositiveIntegerField(verbose_name="piso")),
                ("aula", models.CharField(max_length=20, verbose_name="aula")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
            ],
            options={
                "verbose_name": "solicitud de delivery",
                "verbose_name_plural": "solicitudes de delivery",
            },
        ),
        migrations.AddConstraint(
            model_name="deliveryconfig",
            constraint=models.CheckConstraint(
                check=models.Q(("pk", 1)), name="delivery_config_singleton_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryconfig",
            constraint=models.CheckConstraint(
                check=models.Q(("max_capacity__gt", 0)), name="delivery_max_capacity_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryconfig",
            constraint=models.CheckConstraint(
                check=models.Q(("current_capacity__lte", models.F("max_capacity"))),
                name="delivery_capacity_lte_max",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_request",
                to="orders.order",
                verbose_name="pedido",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(fields=["-created_at"], name="delivery_request_created_idx"),
        ),
    ]
