# Generated by Django 5.0.7 on 2026-09-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rolepermission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='accounts_ro_role_2ac8aa_idx',
            old_name='accounts_rolepermission_role_code_idx',
        ),
    ]
