# Generated by Django 5.0.7 on 2026-09-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CafeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Cafeteria INTESUD", max_length=200, verbose_name="nombre"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descripcion")),
                (
                    "order_open_time",
                    models.TimeField(default="09:00", verbose_name="apertura de pedidos"),
                ),
                (
                    "order_close_time",
                    models.TimeField(default="09:45", verbose_name="cierre de pedidos"),
                ),
                ("break_start", models.TimeField(default="10:00", verbose_name="inicio de receso")),
                ("break_end", models.TimeField(default="10:15", verbose_name="fin de receso")),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=10, verbose_name="capacidad de preparacion"
                    ),
                ),
                (
                    "current_capacity",
                    models.PositiveIntegerField(default=0, verbose_name="capacidad en uso"),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="cafeteria abierta")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
            ],
            options={
                "verbose_name": "configuracion de cafeteria",
                "verbose_name_plural": "configuraciones de cafeteria",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="codigo")),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                ("description", models.TextField(blank=True, verbose_name="descripcion")),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "requires_voucher",
                    models.BooleanField(default=False, verbose_name="requiere comprobante"),
                ),
                ("instructions", models.TextField(blank=True, verbose_name="instrucciones")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
            ],
            options={
                "verbose_name": "metodo de pago",
                "verbose_name_plural": "metodos de pago",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="cafeconfig",
            constraint=models.CheckConstraint(
                check=models.Q(("pk", 1)), name="cafe_config_singleton_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="cafeconfig",
            constraint=models.CheckConstraint(
                check=models.Q(("current_capacity__lte", models.F("total_capacity"))),
                name="cafe_capacity_lte_total",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["active", "order"], name="paymethod_active_order_idx"),
        ),
    ]
