# Generated by Django 5.0.7 on 2026-09-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_cafeconfig_table_alter_paymentmethod_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='titular'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='numero de cuenta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='holder_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='identificacion'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='telefono/celular'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_info',
            field=models.TextField(blank=True, verbose_name='info QR/codigo'),
        ),
    ]
