# Generated by Django 5.0.7 on 2026-09-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_add_paymentmethod_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfig',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='fondo de portada'),
        ),
    ]
