# Generated by Django 5.0.7 on 2026-09-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_cafeconfig_hero_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='imagen QR'),
        ),
    ]
