# Generated by Django 5.0.7 on 2026-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_cafeconfig_home_card_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfig',
            name='login_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/login/', verbose_name='fondo de pantalla de login'),
        ),
        migrations.AddField(
            model_name='cafeconfig',
            name='login_mascot',
            field=models.ImageField(blank=True, null=True, upload_to='site/login/', verbose_name='mascota/panda de login'),
        ),
        migrations.AddField(
            model_name='cafeconfig',
            name='system_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='logo del sistema'),
        ),
    ]
