# Generated by Django 5.0.7 on 2026-09-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='pagos',
        ),
    ]
