# Generated by Django 5.0.7 on 2026-09-06 21:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nombre")),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="icono")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["order", "name"],
                "indexes": [models.Index(fields=["order", "name"], name="category_order_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                ("description", models.TextField(blank=True, verbose_name="descripcion")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="stock")),
                ("min_stock", models.PositiveIntegerField(default=3, verbose_name="stock minimo")),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Tiempo estimado de preparacion en minutos.",
                        verbose_name="tiempo de preparacion (min)",
                    ),
                ),
                ("available", models.BooleanField(default=True, verbose_name="disponible")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/", verbose_name="imagen"
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=10, verbose_name="emoji")),
                ("added_at", models.DateTimeField(auto_now_add=True, verbose_name="agregado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio",
                    ),
                ),
                ("available", models.BooleanField(default=True, verbose_name="disponible")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "adicional",
                "verbose_name_plural": "adicionales",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "available"], name="product_cat_available_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["available", "name"], name="product_available_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="product_stock_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="product_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("stock__gte", 0)), name="product_stock_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("min_stock__gte", 0)), name="product_min_stock_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("prep_time__gte", 0)), name="product_prep_time_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="addon",
            index=models.Index(fields=["product", "available"], name="addon_product_available_idx"),
        ),
        migrations.AddConstraint(
            model_name="addon",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="addon_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="addon",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="addon_product_name_unique"
            ),
        ),
    ]
